name: Generate CLOC Badge

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cloc jq

    - name: Run cloc
      run: |
        cloc --json . > cloc.json

    - name: Extract total lines
      id: cloc
      run: |
        total_lines=$(jq '.SUM.code' cloc.json)
        echo "lines=$total_lines" >> $GITHUB_OUTPUT

    - name: Generate badge
      run: |
        LINES=${{ steps.cloc.outputs.lines }}
        curl "https://img.shields.io/badge/Total%20Lines-$LINES-blue" -o cloc-badge.svg

    - name: Commit badge
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update cloc badge
        file_pattern: cloc-badge.svg
